wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1685476822.433529
    t:
      1:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.0
      5: 0.15.3
      8:
      - 1
      - 3
      - 5
